name: Security check

on:
  push:


jobs:
  sast-scan:
    name: sast scanning AppThreat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: AppThreat/sast-scan-action@master
        with:
          type: "go"

      


