name: Security check

on:
  push:


jobs:
  sast-appthreat:
    name: sast scanning AppThreat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: AppThreat/sast-scan-action@master
        with:
          type: "go"
          output: reports
        continue-on-error: true

      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
          
  sast-shiftleft:        
    name: sast scanning AppThreat
    runs-on: ubuntu-latest
    steps:
      - uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,go,depscan"

  sast-semgrep:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout project source
      - uses: actions/checkout@v3

      # Scan code using project's configuration on https://semgrep.dev/manage
      - uses: returntocorp/semgrep-action@fcd5ab7459e8d91cb1777481980d1b18b4fc6735
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}
          generateSarif: "1"

      # Upload SARIF file generated in previous step
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()


